[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "" # Uses Dockerfile CMD
healthcheckPath = "/healthz"
healthcheckTimeout = 100

[volumes.data]
mountPath = "/data"
